#
# Autogenerated by Sandesh Compiler (1.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:new_style
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

import ttypes

_HTTP_REQUEST_LIST = [
{ 'uri':'/Snh_PodDatabaseList', 'method':ttypes.PodDatabaseList.handle_http_request },
{ 'uri':'/Snh_NamespaceDatabaseList', 'method':ttypes.NamespaceDatabaseList.handle_http_request },
{ 'uri':'/Snh_ServiceDatabaseList', 'method':ttypes.ServiceDatabaseList.handle_http_request },
{ 'uri':'/Snh_NetworkPolicyDatabaseList', 'method':ttypes.NetworkPolicyDatabaseList.handle_http_request },
{ 'uri':'/Snh_IngressDatabaseList', 'method':ttypes.IngressDatabaseList.handle_http_request },
{ 'uri':'/Snh_LoadbalancerDatabaseList', 'method':ttypes.LoadbalancerDatabaseList.handle_http_request },
{ 'uri':'/Snh_LoadbalancerListenerDatabaseList', 'method':ttypes.LoadbalancerListenerDatabaseList.handle_http_request },
{ 'uri':'/Snh_LoadbalancerPoolDatabaseList', 'method':ttypes.LoadbalancerPoolDatabaseList.handle_http_request },
{ 'uri':'/Snh_LoadbalancerMemberDatabaseList', 'method':ttypes.LoadbalancerMemberDatabaseList.handle_http_request },
{ 'uri':'/Snh_HealthMonitorDatabaseList', 'method':ttypes.HealthMonitorDatabaseList.handle_http_request },
{ 'uri':'/Snh_VirtualMachineDatabaseList', 'method':ttypes.VirtualMachineDatabaseList.handle_http_request },
{ 'uri':'/Snh_VirtualRouterDatabaseList', 'method':ttypes.VirtualRouterDatabaseList.handle_http_request },
{ 'uri':'/Snh_VirtualMachineInterfaceDatabaseList', 'method':ttypes.VirtualMachineInterfaceDatabaseList.handle_http_request },
{ 'uri':'/Snh_VirtualNetworkDatabaseList', 'method':ttypes.VirtualNetworkDatabaseList.handle_http_request },
{ 'uri':'/Snh_InstanceIpDatabaseList', 'method':ttypes.InstanceIpDatabaseList.handle_http_request },
{ 'uri':'/Snh_ProjectDatabaseList', 'method':ttypes.ProjectDatabaseList.handle_http_request },
{ 'uri':'/Snh_DomainDatabaseList', 'method':ttypes.DomainDatabaseList.handle_http_request },
{ 'uri':'/Snh_SecurityGroupDatabaseList', 'method':ttypes.SecurityGroupDatabaseList.handle_http_request },
{ 'uri':'/Snh_FloatingIpPoolDatabaseList', 'method':ttypes.FloatingIpPoolDatabaseList.handle_http_request },
{ 'uri':'/Snh_FloatingIpDatabaseList', 'method':ttypes.FloatingIpDatabaseList.handle_http_request },
{ 'uri':'/Snh_NetworkIpamDatabaseList', 'method':ttypes.NetworkIpamDatabaseList.handle_http_request },
{ 'uri':'/Snh_KubeGreenletStackList', 'method':ttypes.KubeGreenletStackList.handle_http_request },
{ 'uri':'/Snh_KubeApiConnectionStatus', 'method':ttypes.KubeApiConnectionStatus.handle_http_request },
{ 'uri':'/Snh_MastershipStatus', 'method':ttypes.MastershipStatus.handle_http_request },
]

